#!/usr/bin/env python3
"""
Phase 37 (0.37.0): the one-off rebrand from ShiftBoard to ShiftUp.

What it does, in the files listed in EXPECT at the bottom (and only those):
  1. Name:   the service's name "ShiftBoard" becomes "ShiftUp" in text people read, comments and docs.
             Code names are left alone (the ShiftBoard.jsx component, shiftboard_* storage keys, database names).
  2. Colour: Tailwind "emerald" classes become "brand" (gold) where they are a button, an active tab, a link,
             a focus ring, a section icon or pay. They stay green where they mean confirmed / booked / on / done.
             White text on a solid gold button becomes dark text.
  3. A few exact one-off swaps (the "Find shifts" wording, the email button colour, the installed app's colours,
             the favicon links, the service worker's cache name).

How to run it, from the repository's root folder (the folder that has docker-compose.yaml):
    python scripts/phase37_rebrand.py --check     look only: says what it would do and changes nothing
    python scripts/phase37_rebrand.py             do it
On Linux or macOS the command may be "python3". It needs Python 3.8 or newer and nothing else.

It is safe:
  * Before it writes anything it checks every file against a SHA-256 fingerprint of the 0.36.1 file, and checks
    that its own result has the expected fingerprint. If anything differs it stops and changes nothing.
  * A file that is already done is skipped, so an interrupted run can be run again.
  * Once Phase 37's hand edits are in, it says "already applied" and changes nothing.
  * Line endings are kept as they are (three files use Windows line endings).

DO NOT EDIT THIS FILE. If it stops with an error, the answer is never to change the rules or the fingerprints:
report the message.
"""
import hashlib
import os
import re
import shutil
import sys

# ---------------------------------------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------------------------------------
# The service's name. Not touched: ShiftBoardModal, <ShiftBoard ...>, ./ShiftBoard, shiftboard (lower case).
NAME = re.compile(r"(?<![A-Za-z0-9_<./])ShiftBoard(?![A-Za-z0-9_])")
NAME_SKIP = re.compile(r"\b(?:import|function)\s+ShiftBoard\b")      # the shift-chat component keeps its code name

# Where the name is changed: every .py / .jsx / .js under these folders, plus these files.
NAME_DIRS = ["backend/src", "frontend/src"]
NAME_FILES = [
    "frontend/index.html", "frontend/public/manifest.webmanifest", "frontend/public/offline.html", "frontend/public/sw.js",
    "README.md", "docs/DEPLOYMENT.md", "product-roadmap.md", ".env.template", "backend/.env.template", "frontend/.env.template",
]
# Where colours are changed.
COLOR_DIRS = ["frontend/src"]

# ---------------------------------------------------------------------------------------------------------
# Colours. Every Tailwind class that uses "emerald" is looked at one by one:
#   B = it becomes brand gold (buttons, active tabs, links, section icons, pay, focus rings, selected options)
#   K = it stays green (it means confirmed / booked / on / success)
# ---------------------------------------------------------------------------------------------------------
TOKEN = re.compile(
    r"(?<![\w-])((?:[a-z-]+:)*)(bg|text|border|ring|accent|from|to|via|shadow)-emerald-(\d{2,3})(/\d{1,3})?(?![\w/])")
QUOTES = re.compile(r"""(['"`])""")
STATUS = re.compile(
    r"Confirmed|Booked|booked|confirmed|approved|checked_in|completed|CheckCircle|ThumbsUp|<Check\b|"
    r"isFull|filled >=|fill_rate|=== 'ok'|\bcopied\b|success|Instant|instant|any_instant|=== 'auto'|<Zap\b|"
    r"\bON\b|Live \u00b7|pct >= 100|Sent 24h|verified|Verified|clocked|Clocked")
INTERACTIVE = ("hover:", "focus:", "focus-within:", "focus-visible:", "active:", "group-hover:")

# Whole-phrase swaps done before the class-by-class pass (the sign-in buttons were a green-to-teal gradient).
PHRASES = [
    ("bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600", "bg-brand-500 hover:bg-brand-400"),
]

# Lines that stay green although the rules alone would turn them gold. (file, a piece of the line)
KEEP = [
    ("frontend/src/components/Navbar.jsx", "userRole === 'venue_manager' ? 'bg-teal-400' : 'bg-emerald-400'"),     # role colour
    ("frontend/src/components/PostedShiftsBoard.jsx", '<div className="h-full bg-emerald-500" style='),             # "filled" bar
    ("frontend/src/components/ActivityFeed.jsx", "bookings: [CalendarCheck, 'text-emerald-400']"),
    ("frontend/src/components/admin/AdminActivity.jsx", "bookings: [CalendarCheck, 'text-emerald-400']"),
    ("frontend/src/components/ShiftDetailsModal.jsx", "from-emerald-600/10 to-slate-950"),                           # your booked shift
    ("frontend/src/components/WorkerCalendar.jsx", "from-emerald-600/15 to-slate-900"),                              # your next shift
    ("frontend/src/components/WorkerCalendar.jsx", "tracking-wider text-emerald-300\">Your next shift"),
    ("frontend/src/components/WorkerCalendar.jsx", "text-lg sm:text-xl font-bold text-emerald-300 flex items-center gap-2"),
    ("frontend/src/components/EventListingModal.jsx", '<p className="text-xs text-emerald-300/80 mt-1">'),            # under "You're booked"
    ("frontend/src/components/EventListingModal.jsx", "A spot opened and it's being held for you."),
    ("frontend/src/components/EventTemplatesPanel.jsx", "t.location.is_archived ? 'text-amber-300' : 'text-emerald-300'"),
    ("frontend/src/components/PushDeviceCard.jsx", "text-xs font-semibold text-emerald-300 inline-flex items-center gap-1.5 mr-auto"),
    ("frontend/src/components/TeamModal.jsx", "active: ['On your team', 'text-emerald-300']"),
    ("frontend/src/components/TeamModal.jsx", "worked: ['On your team (worked here)', 'text-emerald-300']"),
    ("frontend/src/components/TeamModal.jsx", "invited: 'text-emerald-300'"),
    ("frontend/src/components/TimesheetModal.jsx", "tips.locked && <span className=\"text-[10px] font-semibold text-emerald-300"),
    ("frontend/src/components/TimesheetModal.jsx", "{notice && !dirty && <p className=\"text-xs text-emerald-300\">"),
    ("frontend/src/components/admin/AdminOverview.jsx", '<p className="text-sm text-emerald-300 flex items-center gap-2 py-2">'),
    ("frontend/src/components/admin/AdminUserDrawer.jsx", "active: ['On team', 'text-emerald-300']"),
    ("frontend/src/components/admin/AdminUserDrawer.jsx", '<b className="text-emerald-300">on</b>'),
    ("frontend/src/components/admin/AdminVenues.jsx", '<span className="text-emerald-300 inline-flex items-center gap-1"><Crosshair'),
    ("frontend/src/components/manager/PayPeriodsModal.jsx", '<p className="text-xs text-emerald-100 flex items-start gap-1.5">'),
    ("frontend/src/components/worker/WaitlistPanel.jsx", "text-sm font-bold text-emerald-100"),
    ("frontend/src/components/worker/WaitlistPanel.jsx", '<Hourglass className="w-4 h-4 text-emerald-300" />'),
    ("frontend/src/pages/OrganizationPage.jsx", "t.live_now ? 'text-emerald-300' : 'text-white'"),
    ("frontend/src/pages/OrganizationPage.jsx", "font-normal text-emerald-100/70"),
    ("frontend/src/pages/WorkerDashboard.jsx", "text-[11px] text-emerald-300\">You're in line for"),
    ("frontend/src/components/worker/MyShiftCard.jsx", '<span className="text-xs text-emerald-400 font-semibold inline-flex items-center gap-1">'),   # "Worked"
]

# Lines that turn gold although the rules alone would leave them green: selected options, on/off filter
# buttons, plain decoration, and pay. (file, a piece of the line)
GOLD = [
    ("frontend/src/components/AppNudge.jsx", "border border-emerald-500/40 bg-emerald-500/5 flex items-start gap-3"),
    ("frontend/src/components/DuplicateEventModal.jsx", "mode === id ? 'border-emerald-500 bg-emerald-500/10 text-emerald-300'"),
    ("frontend/src/components/EventListingCard.jsx", "text-emerald-300 border border-emerald-500/30 text-[10px] font-bold whitespace-nowrap"),
    ("frontend/src/components/EventListingModal.jsx", "'border-emerald-500 bg-emerald-500/10 ring-1 ring-emerald-500/40'"),
    ("frontend/src/components/EventListingModal.jsx", "on ? 'border-emerald-500/50 bg-emerald-500/5'"),
    ("frontend/src/components/EventListingModal.jsx", "text-emerald-300 border border-emerald-500/40 font-bold disabled:opacity-50"),
    ("frontend/src/components/EventListingModal.jsx", 'className="text-sm font-black text-emerald-400" hiddenText='),
    ("frontend/src/components/EventLocationPicker.jsx", "border border-emerald-500/40 bg-emerald-500/5 space-y-3"),
    ("frontend/src/components/EventLocationPicker.jsx", '<p className="text-[11px] text-emerald-200">'),
    ("frontend/src/components/EventRosterModal.jsx", "bg-emerald-600/15 hover:bg-emerald-600 text-emerald-300 hover:text-white"),
    ("frontend/src/components/PostedShiftsBoard.jsx", "bg-emerald-600/20 hover:bg-emerald-600 text-emerald-300 hover:text-white"),
    ("frontend/src/components/ShiftRosterModal.jsx", "bg-emerald-600/20 hover:bg-emerald-600 text-emerald-300 hover:text-white"),
    ("frontend/src/components/ShiftRosterModal.jsx", "rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30"),
    ("frontend/src/components/WorkerProfilePanel.jsx", "rounded-full bg-emerald-500/15 text-emerald-300 border border-emerald-500/30"),
    ("frontend/src/components/ShiftDetailsModal.jsx", 'className="text-lg font-black text-emerald-400" hiddenText='),
    ("frontend/src/pages/VenueProfile.jsx", 'className="text-sm text-emerald-400 font-semibold" hiddenText='),
    ("frontend/src/components/StaffPositionModal.jsx", "isSel ? 'border-emerald-500/60 bg-emerald-500/5'"),
    ("frontend/src/components/TeamModal.jsx", "on ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40'"),
    ("frontend/src/components/TeamModal.jsx", "open ? 'border-emerald-500/40 bg-slate-950'"),
    ("frontend/src/components/VenueSettingsModal.jsx", "form.approval_policy === p.id ? 'border-emerald-500 bg-emerald-500/10'"),
    ("frontend/src/components/VenueSettingsModal.jsx", "form.team_time_tracking === t.id ? 'border-emerald-500 bg-emerald-500/10'"),
    ("frontend/src/components/WorkerCalendar.jsx", "isSelected ? 'ring-2 ring-inset ring-emerald-500 bg-emerald-500/5'"),
    ("frontend/src/components/manager/PayPeriodsModal.jsx", "selected === p.start_date ? 'border-emerald-500/60 bg-emerald-500/5'"),
    ("frontend/src/components/manager/TodayEventCard.jsx", "bg-emerald-600/20 border border-emerald-500/40 text-emerald-200"),
    ("frontend/src/components/manager/TonightBoard.jsx", "border-emerald-500/40 bg-emerald-600/20 text-emerald-200"),
    ("frontend/src/components/profile/AboutSection.jsx", "on ? 'border-emerald-500/60 bg-emerald-500/10'"),
    ("frontend/src/components/profile/AboutSection.jsx", "bg-emerald-500/10 border border-emerald-500/30 text-emerald-200 text-xs"),
    ("frontend/src/components/profile/CalendarSyncPanel.jsx", "w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center flex-shrink-0\">"),
    ("frontend/src/components/profile/CalendarSyncPanel.jsx", '<CalendarPlus className="w-5 h-5 text-emerald-300" />'),
    ("frontend/src/components/profile/TimeOffPanel.jsx", "rounded-2xl bg-slate-900 border border-emerald-500/30 space-y-4"),
    ("frontend/src/components/profile/TimeOffPanel.jsx", "on ? 'bg-emerald-500/15 text-emerald-200 border-emerald-500/40'"),
    ("frontend/src/components/worker/CoverDialog.jsx", "audience === id ? 'border-emerald-500 bg-emerald-500/10'"),
    ("frontend/src/components/worker/CoverDialog.jsx", '<Icon className="w-4 h-4 mt-0.5 text-emerald-300 flex-shrink-0" />'),
    ("frontend/src/components/worker/EarningsCard.jsx", "w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30"),
    ("frontend/src/components/worker/MyShiftCard.jsx", "bg-slate-800 hover:bg-slate-700 text-emerald-300 border border-emerald-500/40"),
    ("frontend/src/pages/LoginPage.jsx", "border border-emerald-500/40 bg-emerald-500/10 text-sm text-emerald-100 text-center"),
    ("frontend/src/pages/PublicBoardPage.jsx", "p.open_spots > 0 ? 'bg-emerald-500/10 text-emerald-200 border-emerald-500/30'"),
    ("frontend/src/pages/VenuesDirectory.jsx", "bg-emerald-500/15 text-emerald-400 border border-emerald-500/30"),
    ("frontend/src/pages/WorkerDashboard.jsx", "instantOnly ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40'"),
    ("frontend/src/pages/WorkerDashboard.jsx", "hideRequested ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40'"),
    ("frontend/src/pages/WorkerDashboard.jsx", "fitsOnly ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40'"),
    ("frontend/src/pages/WorkerDashboard.jsx", "mineOnly ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/40'"),
]


def decide(pref, util, shade, alpha, line, seg, path):
    """'B' = brand gold, 'K' = keep green."""
    for p, piece in KEEP:
        if p == path and piece in line:
            return "K"
    for p, piece in GOLD:
        if p == path and piece in line:
            return "B"
    shade = int(shade)
    interactive = any(x in pref for x in INTERACTIVE)
    status = bool(STATUS.search(line))
    if util in ("accent", "from", "to", "via", "shadow"):
        return "B"
    if util == "ring":
        return "B" if (interactive or not alpha) and not status else "K"
    if util == "bg":
        if alpha or shade >= 900:                      # a tinted or very dark surface is a status surface
            return "K"
        return "K" if status and not interactive else "B"      # a solid fill is a button, a tab or a dot
    if util == "border":
        if interactive:
            return "B"
        if alpha or shade >= 700:
            return "K"
        return "K" if status else "B"
    # text
    if interactive:
        return "B"
    tinted = bool(re.search(r"(?:bg|border)-emerald-\d{2,3}/\d", seg)) or bool(re.search(r"bg-emerald-9\d0", seg))
    return "K" if (tinted or status) else "B"


def gold_class(pref, util, shade, alpha):
    shade = int(shade)
    if util == "bg" and not alpha and shade in (400, 500, 600):
        if "hover:" in pref:
            shade = {400: 400, 500: 400, 600: 500}[shade]        # a hover is one step lighter than the button
        else:
            shade = min(shade, 500)                               # every solid button is the logo's gold
    return f"{pref}{util}-brand-{shade}{alpha}"


def recolor_line(line, path):
    for old, new in PHRASES:
        line = line.replace(old, new)
    if "emerald" not in line:
        return line
    out = []
    for seg in QUOTES.split(line):                    # one quoted class list at a time
        flip = {"base": False, "hover": False}

        def swap(m, seg=seg, flip=flip):
            pref, util, shade, alpha = m.group(1), m.group(2), m.group(3), m.group(4) or ""
            if decide(pref, util, shade, alpha, line, seg, path) != "B":
                return m.group(0)
            if util == "bg" and not alpha and int(shade) in (400, 500, 600):
                flip["hover" if "hover:" in pref else "base"] = True
            return gold_class(pref, util, shade, alpha)

        new = TOKEN.sub(swap, seg)
        if flip["base"]:                              # white text can't be read on gold
            new = re.sub(r"(?<![\w:-])text-white(?![\w/-])", "text-slate-950", new)
        if flip["hover"]:
            new = re.sub(r"(?<![\w-])hover:text-white(?![\w/-])", "hover:text-slate-950", new)
        out.append(new)
    return "".join(out)


# One-off wording and colour swaps, made after the rename. (file, exact old text, exact new text); each old
# text is in its file exactly once.
SWAPS = [
    # the worker's "Find shifts" tab is now called ShiftBoard
    ("frontend/src/components/profile/AvailabilityEditor.jsx", '<b className="text-slate-200">Find shifts</b> can hide', '<b className="text-slate-200">ShiftBoard</b> can hide'),
    ("frontend/src/components/VenueSettingsModal.jsx", "for anyone on Find shifts.", "for anyone on the ShiftBoard."),
    ("frontend/src/components/worker/CoverDialog.jsx", "'Also listed on Find shifts for anyone.", "'Also listed on the ShiftBoard for anyone."),
    ("frontend/src/pages/JoinPage.jsx", "You'll see their shifts in Find shifts and get alerts", "You'll see their shifts on the ShiftBoard and get alerts"),
    ("backend/src/services/notify_cover.py", "Open Find shifts to take it.", "Open the ShiftBoard to take it."),
    ("backend/src/routers/staffing.py", "Request it from Find shifts.", "Request it from the ShiftBoard."),
    ("frontend/public/manifest.webmanifest", '{ "name": "Find shifts", "url": "/worker?tab=find"', '{ "name": "ShiftBoard", "url": "/worker?tab=find"'),
    # "the public shift board" (where cover requests can be listed for anyone) is the ShiftBoard
    ("frontend/src/components/VenueSettingsModal.jsx", "Workers can post cover on the public shift board", "Workers can post cover on the ShiftBoard"),
    ("frontend/src/components/worker/CoverDialog.jsx", "'My team + the public shift board'", "'My team + everyone on the ShiftBoard'"),
    ("backend/src/services/notify_cover.py", '" Posted on the public shift board too."', '" Posted on the ShiftBoard too."'),
    # the shift chat was labelled "Board" in three places; that word now means the ShiftBoard
    ("frontend/src/components/ShiftDetailsModal.jsx", '<MessageSquare className="w-4 h-4 text-indigo-400" /> Board', '<MessageSquare className="w-4 h-4 text-indigo-400" /> Shift chat'),
    ("frontend/src/components/EventRosterModal.jsx", '<MessageSquare className="w-3 h-3" /> Board', '<MessageSquare className="w-3 h-3" /> Chat'),
    ("frontend/src/components/ShiftBoard.jsx", "No messages yet on this shift board.", "No messages yet in this shift chat."),
    # names of files people download
    ("backend/src/services/earnings.py", 'name = f"shiftboard-hours-{data.start_date.isoformat()}', 'name = f"shiftup-hours-{data.start_date.isoformat()}'),
    ("backend/src/routers/public.py", """'inline; filename="shiftboard.ics"'""", """'inline; filename="shiftup.ics"'"""),
    # brand colours outside Tailwind
    ("backend/src/services/messaging.py", "background:#10b981;color:#0f172a;text-decoration:none;font-weight:700;padding:10px 16px",
     "background:#FDD400;color:#0a0a0a;text-decoration:none;font-weight:700;padding:10px 16px"),
    ("frontend/public/offline.html", "background: #10b981; color: #020617;", "background: #FDD400; color: #0a0a0a;"),
    ("frontend/public/offline.html", "background: #020617; color: #e2e8f0;", "background: #000000; color: #e2e8f0;"),
    ("frontend/public/offline.html", '<meta name="theme-color" content="#0f172a" />', '<meta name="theme-color" content="#000000" />'),
    ("frontend/public/manifest.webmanifest", '"background_color": "#020617"', '"background_color": "#000000"'),
    ("frontend/public/manifest.webmanifest", '"theme_color": "#0f172a"', '"theme_color": "#000000"'),
    ("frontend/index.html", '<meta name="theme-color" content="#0f172a" />', '<meta name="theme-color" content="#000000" />'),
    ("frontend/index.html", '<link rel="icon" type="image/svg+xml" href="/icons/favicon.svg" />',
     '<link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32.png" />\n    <link rel="icon" type="image/png" sizes="64x64" href="/icons/favicon-64.png" />'),
    # the offline page and the icons changed, so the service worker keeps a new copy
    ("frontend/public/sw.js", "const CACHE = 'shiftboard-shell-v1';", "const CACHE = 'shiftup-shell-v2';"),
]


def rename_line(line):
    if NAME_SKIP.search(line):
        return line
    return NAME.sub("ShiftUp", line)


def transform(text, path):
    """text with LF line endings -> the rebranded text"""
    do_name = path in NAME_FILES or any(path.startswith(d + "/") for d in NAME_DIRS)
    do_color = any(path.startswith(d + "/") for d in COLOR_DIRS)
    lines = []
    for line in text.split("\n"):
        if do_color:
            line = recolor_line(line, path)
        if do_name:
            line = rename_line(line)
        lines.append(line)
    text = "\n".join(lines)
    for p, old, new in SWAPS:
        if p == path:
            if text.count(old) != 1:
                raise SystemExit(f"STOP: {path}: expected exactly one {old!r}, found {text.count(old)}")
            text = text.replace(old, new)
    return text


# ---------------------------------------------------------------------------------------------------------
# The files this script changes: path -> (SHA-256 of the 0.36.1 file, SHA-256 of the finished file).
# Fingerprints are of the text with Unix line endings, as UTF-8.
# ---------------------------------------------------------------------------------------------------------
EXPECT = {
    ".env.template":
        ("be16ee44c7e10c4acae6f72d77c7ad47ed3f71f4b6b3b5c6054b0c16276924a0",
         "ae49005823000b8e3c59bc0e8fd5a3478a663512a9e51dc89d22d5d15195b671"),
    "README.md":
        ("c044655398161def80b02d7837409f760044a45c66ce6946f830c5dad3b43022",
         "8cdb4b008d47e29fc5472bfc52972ff84eb9efb33b163552da439e652e74d9bd"),
    "backend/.env.template":
        ("dd4be4f3a6bd519af16e019c757dd1c3f86f3707c74e58a88d690dd5c6b72c59",
         "cd0ac951c7feb70d5f3c86b6e24b88a560f35ec4234a9c0d680061ca3be66502"),
    "backend/src/__init__.py":
        ("dcdba8c1cc50a20c28ca5700e89b58940b364e2d27c972c1620c91f584a1f475",
         "af681e212977c20cffb4c21236456def504861762b463bd09f5908654cb4bdd7"),
    "backend/src/auth.py":
        ("bf6866e3c2ec98eda19651436952c580ece7f48352c939250946f0d01c9bf7fd",
         "7a3493a9372d6c2e182bd1da66ebe94b16bb208ffe51bc17020dc6e0ee946b98"),
    "backend/src/config.py":
        ("f89f5b872c14ac7164d14e2c30de6661781401e29a32a899e2c560b1c54829f8",
         "f3848edcf3c243de4e12a0973c3e21b3706a55d2e5f3eb87aa796f01a8658b95"),
    "backend/src/demo_data.py":
        ("643cb7890709533981a63e7aa26376299ff4e6c5f2211abf345ee2d5c093d341",
         "e7f0c4d2b50ebdb0e458bdcd1babd8c22d2b700001bf2f561404872c78c819fc"),
    "backend/src/main.py":
        ("36b76779cdbe4c17ebbfa7c4ab65c28f648be87b57a4a334bb29f6d8c844cea5",
         "a345a9233743df2e7538cece49a1470f0228c9b059ffa4dba3abb3aaca68a304"),
    "backend/src/routers/__init__.py":
        ("b56ce4e17f379dd33c900c5b1e40b47a26ecf771d21a0a726b0b8726c12585d5",
         "4b77b8867f3461a701e2a493cb0d131425ccb6965941a429e81dbf207ee2586e"),
    "backend/src/routers/admin.py":
        ("108df8bef4a095e93f3faa7da9f3f8966a00e1fd7f5aacc705b71d489ba3dbd4",
         "52c4f840d267bf01b06ebfe857dc163c081a05ed660a5725c2b4061aa9be78f9"),
    "backend/src/routers/admin_console.py":
        ("99fb2c9c64c5332f22189b7fd12118e62296af07e72673919deb95f1075a7991",
         "446987c94e4f07b1c316cfee3d2d2bb50f9857665453c022186b3743a35814b0"),
    "backend/src/routers/auth.py":
        ("03464dc60e00b65ca5b231b01a1f6d2fe4038aa993a5105d3e2d358f4a4ba339",
         "51f353ab100df8aa84b06d99fb2d9aa15ec4f78c340a816678951507ae30cb00"),
    "backend/src/routers/notifications.py":
        ("918df132531f2e1aaf7625f1c7569f7676908a8d40343a743ff1202fd11d6ea6",
         "c9dc220df5fb038a33ca0a1afc9ad5b2d292c7fb63b90f638c656673833d2842"),
    "backend/src/routers/public.py":
        ("72a9dc3ee66a2c902c072a19dab837a3b02ef197a0ce0c17b48ff08fdc508ece",
         "805d85e05a1eaaeb158028a8854a03ef1de088aa230665fcb82c6cf65e44db56"),
    "backend/src/routers/staffing.py":
        ("86e1094fcc13ad5c92c7ccf9cad10b8db8f73e6976451f78b3db502a2fdaa8ec",
         "8ab1dfec231cc7291d453c878084e144382e8c95f5fdfbfce32d8351486a8d29"),
    "backend/src/routers/team.py":
        ("f2b082cb5fda5b6f08d9a38ab38f0e1406f32ef33ba01fbe67aff91ca4a2028a",
         "21274bd4e6c3c43e21dc78829c789d1ed5b97683e48f2573af0e13784ee76541"),
    "backend/src/routers/venues.py":
        ("2ed64553bf87b27076d84a124c0673ccd5327bee2229b38d4d7ffe86f8c95536",
         "127d13488a05f48605f836393a8b84378a2fb3484a47ef78c7bf20e83305d9eb"),
    "backend/src/seed.py":
        ("978e28dd7b63a10c5a05e00fef7982773a1fe899a8f83878dfabd1a5995c7568",
         "2529799b0ffcbc5fb7c52d5399ae4a41c2b4bd49df556c6df3602d27a40fcaa0"),
    "backend/src/serializers.py":
        ("5cfa3f2c91c1ba8a7c7e4079971af1cbc75ce890ad31f9b11bd4396706e85b36",
         "51369d1d08e1171ea8e1118556bdd64bac37146a113a46256630180bf81ba505"),
    "backend/src/services/auto_confirm.py":
        ("ae743d928b05139156b0dddcc90001aaa716980c625454879b2453d97688991f",
         "16ea63c75dc8bb4bca7bedee5b57728d93671814be6b882ba214835224245bce"),
    "backend/src/services/calendar_feeds.py":
        ("91638d27d23bb161f4f009d849ef375ef37a31522d6ad8b08653eda93241eef5",
         "83e4ac528432e63dbabaed81627ec38023e29b00c73fbfdd3f4c48c85d4ae6dc"),
    "backend/src/services/clock.py":
        ("5cfb9ddee5566151a59f42eecff802ba293a87e1e89ac4033a2a03516fff6e59",
         "12a0de8c0f2f85c2fd2b5a2ff0f95bd1525871cd7f60f6f0977e95880f16c686"),
    "backend/src/services/earnings.py":
        ("b487c34ea695f023030f675c46fdf5398ff82cae501b3db3b837db8c1e95adb4",
         "57c671dabd9ac18601358cdfc296b8cc7ea4719c3057747067097980b671a694"),
    "backend/src/services/fcm.py":
        ("a80228979959c19a60d939a7a97502426e22a94a8f9d6faeba1d3957dc074316",
         "58281f802b1b201fcf9a921639fa5aa620b928cfe25bbe752a36c85e36671cee"),
    "backend/src/services/invites.py":
        ("e9d3fda883840f07255f5482e60b6fb5b7fd6461a7f643fd5f64f14d65349fd9",
         "afcfdea57cf60967c36dce64b57123a1c7ce7eb9da54c4c4b6def25f0b65d7c5"),
    "backend/src/services/messaging.py":
        ("6bba9da05c61f4a62dcb855eb137f28a93a65a20de84453c73e02bca779b5bf3",
         "feeeaa6a56dff92b9af799c5d227362dc853f2d5d9b6da3a5d245bcad77a21ba"),
    "backend/src/services/notify.py":
        ("2b5d108be407dae4e00cdf9da0d8dbd0155a2039a9990972831c0d5477e93603",
         "f0e7e89a35fdb77ff0a69ccf135caf8411338471b3e42230f13aea7c654a8b43"),
    "backend/src/services/notify_cover.py":
        ("37df3fb47cf9b3dc9ffc1e084839a7bb407ba1cd8ab8b08350e23e05ffbda370",
         "5ca21d64e4c29a56f49a12b9807dbe81f5760bfac403002b1a576a4592af79dd"),
    "backend/src/services/pay_periods.py":
        ("5c94b728e1090da19fbee527634c081f91b00249692b30eb225e16c01ace4531",
         "341d9ad15a745d8a8f7f931c733e021bcfba343cffbf5fa6fec054dddebc3a3b"),
    "backend/src/services/reliability.py":
        ("d81474ee0cb47ab7b466b47c68533ed1ac8750bf682aaa83a516770fdd7f467a",
         "0004a72f2f0ebd88ab8a0a0aae1e9a8232b311aaaa2b97b0d7a6f673119fc9d9"),
    "backend/src/services/time_tracking.py":
        ("1ae806a966563c7cda46d8a531d7bda46eefdfd987e1b1f5083078b1cd084d92",
         "e14ec148e3d2ad2a817c81073295331baaa4a5f19f41a56edc5b456ab30673e2"),
    "backend/src/services/tips.py":
        ("67a7c039c77f3829bcae7ecf7f2208e2afecdff23865c5575717f38f212c66f9",
         "c3d073d87e7d395d9717c51e13e5ae0a9f8a418bd1588ba241592639c0834b16"),
    "backend/src/services/tonight.py":
        ("586901fcab465e8dd7e049879cfb91ca205168795a9228740c081a1755b443d3",
         "98f1764cf7e1bafb0ddd6d6b247e658d2bf1275a1a9b953439ba88b0dbf446eb"),
    "docs/DEPLOYMENT.md":
        ("0d85027401396d8dd439e9f1d6d0aa5b158b080dc181cd1b1b0f93bbe824d9f7",
         "36d57889bdad4d94c0392b24970eae9d0cf648556719e84499e3721f1128ff2f"),
    "frontend/.env.template":
        ("c89dff1850c208d24381ea40c95cfef73aa798bee69dc97c49f9d6b799334852",
         "8bbbb4fdb7da1797fa8575ca2313c832e6167ff7485e0bf7b30704fd2b15d6f6"),
    "frontend/index.html":
        ("100c5d1f4832bb9f599761ed80bf992b58d205da9b05bf637ca6e455c79756df",
         "21fd809e1856ec38939231f9033533c67ae7bde5513ecdd41ccfcb6ef2244893"),
    "frontend/public/manifest.webmanifest":
        ("1db497e50bfe365fd0987357120e6fe1410a089d583c84000700677818fb0942",
         "4891cd51664707afef23af87c07ef5cbc57ee0c462e1cf2c8975d70ba4650204"),
    "frontend/public/offline.html":
        ("2c211aa1cfd25b4d48c90ac078bda3cbfd5c52e880c2455370e8154cfff9ddeb",
         "8299399eaa5536bead699d04621e9a79c1af74c2e96a9511be2b0cba7db84fb8"),
    "frontend/public/sw.js":
        ("89dec41264dd63121a211f6bcf196ac6318bbc41829ce300b183f979b2615604",
         "88efaeef04ce97267aa8117a5933fbc1331beac9d482cd1599cc8ed3e3a4aeba"),
    "frontend/src/App.jsx":
        ("19948f5d1cb097a1808e39b62820c8cf060f95883445280a8d3b7b48e2c44f7e",
         "4a9491364fcf21bc19109ea051e63db155b4e0498303ae1293c8a7cf3ce5e42a"),
    "frontend/src/components/ActivityFeed.jsx":
        ("bd654789896c544989ca38cafc1666256a56dbe5e30e190264892f6980c84bbb",
         "c01e52b55db5c242fd525766f83d792085fd5f5d2ae14e5ab006fe29fc37ad8e"),
    "frontend/src/components/AppNudge.jsx":
        ("cdfe5188299178d06eae3dce983b3c6bc4ec33bafca8f4bd2acda91ff5a72168",
         "2df45e121eabc7f932e5bfbdd4efa2d48d5fd1228eb03bc8f5d5f526276a18e1"),
    "frontend/src/components/ConfirmDialog.jsx":
        ("cda906ac5531fdf4ce2040e30a46c46b77b9dfae0c26e547a517dd004382a256",
         "67b42f030e5c9ed3f878a0adf587fca0820ca762b1fb048e00bb30c1778053d9"),
    "frontend/src/components/DuplicateEventModal.jsx":
        ("f2d32c335908ddaf57d37cac35080bc34ca4ccd9efb3e299de0a9559023f53fd",
         "328422c2b4250166d6b60153551ca5151e64131ba799bff22276b30abdd9abc0"),
    "frontend/src/components/EventListingCard.jsx":
        ("fa0cf13b0658e5aec259714abc20f539ad227ae88955e4b96f878476ea602b73",
         "0559dad4f9f4a1d22be1860a8082bc77a38e03d3a872a1209d653157f6593e6c"),
    "frontend/src/components/EventListingModal.jsx":
        ("ac1c1f6731291dcfd58b8ae40531972795770c25d93ca6ae15460028243790e9",
         "1f628f8bbd16d20d0bc1220977765111a81cb4fd162528234f0f1b09738434dd"),
    "frontend/src/components/EventLocationPicker.jsx":
        ("0e04c3eb8dd8110f8efc8aeca434a1bc37b4bd3cb9f3af048e6e8ffb30f2e556",
         "eb2d36c36332523dbb0674f27d9cfd8ea0368afba4de029972c9f95e0c807f51"),
    "frontend/src/components/EventRosterModal.jsx":
        ("1c5976baf46199548b0ad84468463e395d0882f70030bc595dc390b85a85b2d9",
         "a81b45d31e18b4a591df29313cfc6a6450763959b35d09749002b4c3746362e3"),
    "frontend/src/components/EventTemplatesPanel.jsx":
        ("eb60f4a34c892722649685af6165475e2d243f2de2cfc2ccc5caba9417aa521d",
         "d89948e9d1625b51a1442116857d61dd79457074481d4da6710461a5f9b829b1"),
    "frontend/src/components/LocationFields.jsx":
        ("b2e153a74526de6f01e5a20008a72468b469ee05339a1be23b0058ef16efcf4f",
         "bc74d927593d84234ef50947daf2baf88b1080fb204fdc41a50b02ac8340d4e7"),
    "frontend/src/components/ManagerQueues.jsx":
        ("9a487dfaa96ec0435c8c5134f390c8709023062346f6b832b0f5830a705605a0",
         "c9412274c3268f4f8672519cff1a6abf91a8ca0ca86c45c54a411c4663c70ae8"),
    "frontend/src/components/Navbar.jsx":
        ("1de63a969feb1f58d50718da1ab1dcbe76fbc3edae1204bbe5ae16a7b27623e4",
         "9006ec0682ffe2a5256a84afc37ff202b3572f3cd98c6e96be83ee927ffcb274"),
    "frontend/src/components/NotificationBell.jsx":
        ("12e5424d4a879ddbff22359cd5be3c2a41b80162499a69e60cbdafee8cd2abde",
         "e4a15a1fbb45c18c54f5fb392d17dfbc99939136c65fe567c5eb396f7a27377c"),
    "frontend/src/components/NotificationSettingsModal.jsx":
        ("8c85d815bd4eac72b9fbf2e111ad9d7045ba3eaed64afed3d782507fd4c2acd8",
         "91374ae64d447e83a1e1d5c9e472050e0f083bea45dd49dc91afdf1bed8685f9"),
    "frontend/src/components/PostedShiftsBoard.jsx":
        ("3faa58ef2778b791fb58e5e17140f27a8b3dfff722f496d0803bd0f17e45cddc",
         "a7173f9924982ce17eeb3f403c1da58365e146d931b022f6987ef33dcf4be413"),
    "frontend/src/components/ProtectedRoute.jsx":
        ("d8b73bc22c9f465dc7a0dba4218d750215fbfa20e1718a2c1884ae1a9b303e96",
         "1c6e4570fa344ad09b4f2460b6a649b99fb0e9168ead1ceed9f086eb447fdc0b"),
    "frontend/src/components/PushDeviceCard.jsx":
        ("5462d3bc033174a82bff497310b9613c73cddb00be592b929fecb61d38ec1682",
         "3b46efe306576485b9ade752a2436a3fc37e90f029b9a52bbe1903f93ea026d9"),
    "frontend/src/components/ReasonDialog.jsx":
        ("c6df6c37baac3777cbb997144d746434994b773385c1dce5285989af21717cdd",
         "d150af150a68ac63f0ea2072151a3b9c55636677d134d53576ea4d224288ed99"),
    "frontend/src/components/ResetPasswordModal.jsx":
        ("acfebf91e33165c6397be4485d0f7cd2aaac5cc77b7de99f4199e477dcb0afbb",
         "f298222e2d071a01967e936bd7c70111307f106517db77ea82585befc0f8f007"),
    "frontend/src/components/ReviewModal.jsx":
        ("a8c59c208fae02199834940dec30fdb2d97f8590171e88a80bd2e7b77a84c2fb",
         "369573cd745cd54cf0004605e280a5b39d73191d4e0d61624364e6c14e8481aa"),
    "frontend/src/components/ShiftBoard.jsx":
        ("92ebdd90a292ad90dbe43a4a3893a8bf9ab30808e362c11967374beb149821f0",
         "a63958a1fe67efa017f21ffdd2072a6248abb1cdcf82018fbf0000a3aad290de"),
    "frontend/src/components/ShiftDetailsModal.jsx":
        ("cf7ea42f72119536d38b34e6b186eea51088a422328af15723208814b5f05cf1",
         "c55c5c7e7cf2407d678e528dbff72e2a761d4681d4f90a2f508da633fdd5c55f"),
    "frontend/src/components/ShiftEventFormModal.jsx":
        ("c7bdda8ba2f58b5c88e73d77991bfebd8c07d31c4f75bac011e44ab2c8ef9218",
         "2574e43468ba60b5112c8e171a93332305d6f08f59969b4ebb18bdff6867ce71"),
    "frontend/src/components/ShiftRosterModal.jsx":
        ("4699c7c36a5d517965372db09b7fce5bcc65c29dd573ad6dc9214543e7c4f8df",
         "747624aa0c54ef2f73628a3b4f264586089167092c5f6d6719111e06adf7b1da"),
    "frontend/src/components/StaffPositionModal.jsx":
        ("24a256a41ca4c5b7ac2a0ffbfcbf68c8519e1e146ab873a6dd185af4e37b9025",
         "005018f51d9132c04b62fc7ec140149f31d0c868011cb51f59489b29e20582eb"),
    "frontend/src/components/TeamModal.jsx":
        ("a0e32ff4e0cde268c9f4f44840894c89c5900b8a881adca29304971e805fac50",
         "2560e4eda262d328993129bf17a6bc1bce07fcaf464c96ed989c99d645beda52"),
    "frontend/src/components/TimesheetModal.jsx":
        ("576ceea97f31ab5ffc990ecb3feaa223fbf5fcd5f96ce0524525828a1e385778",
         "f0561b983bc64a7dba78cd6da8a2ca5b820dba308c750774325757de4237f70f"),
    "frontend/src/components/VenueLocationsPanel.jsx":
        ("1d4223d524619f951780d7c9998101ad6b0403de6b3b270406e4851e157ed2f3",
         "3efade5d34a8f04c11ce813299ee58b1f17a7ede8fae76750fe05ed50aad8d17"),
    "frontend/src/components/VenueSettingsModal.jsx":
        ("672d514aec591e3440e18d4a92e32ac014b60e84786c703bc88968146ab62b17",
         "fd71afdb1ceca5f6ee6f704e2315862c83afc4461be185ebb63fdb8efecb6f44"),
    "frontend/src/components/WorkerCalendar.jsx":
        ("594916dc8cf96e2f7b185f99e1437088e36ffd6d8155bde1f0cc0e0cbb850692",
         "5f27d76fea6e87023adc2e6a73afeff234d1cbedb4060d9c7f88bb40e40df761"),
    "frontend/src/components/WorkerOffers.jsx":
        ("e3d27a66d1aaf9764551f49ed1c6688c26ce0362eafb053bf49f548322e5e492",
         "cf58b49db93750cff73e79ae1430979ff506f874a43b222819d2d8b7d86885bb"),
    "frontend/src/components/WorkerProfilePanel.jsx":
        ("c86c8a0cc6bc632d33a90967958af210dcf3f7a9a1512c3ce99ce0960df0fef3",
         "eed385c3eb63e3bec9031833fc2d01d0520de21a6a59fe6efedf01a0cc538ea3"),
    "frontend/src/components/WorkerTabBar.jsx":
        ("e68e122e1650be78091dd3b6789f3e1af9bfbe9c6ea0ba595f9886c2a6124c36",
         "75c9ae935166639726cedd0430aeaa102276977f11ff02dc7f81b81177e8ceb5"),
    "frontend/src/components/admin/AdminActivity.jsx":
        ("75ccad71cdde714865ff31dd0c8c0ae366eb482560cdab6bcf53c5a1bb42ed5d",
         "6e2f4c729640267eaccf9b0c1fe00ada3226225f489d179fb970bab378b5fe3f"),
    "frontend/src/components/admin/AdminCreateUserModal.jsx":
        ("0477d9e1565775b053501fccfa7afce978d77b3b7e602fe3f51908cc26dac11a",
         "e5dff85bea075da196382d6f19957faf5ea207d86925b83b81fbe908008591b7"),
    "frontend/src/components/admin/AdminOverview.jsx":
        ("ecef6e8b8ac3f25814b9c0fae395e1a19426c9132ea950bf4a43644867a267d8",
         "ba5a2725ea94eec684805352304556ab88ef3c5d0f00473f31293cd0e28bda33"),
    "frontend/src/components/admin/AdminSystem.jsx":
        ("4da166565a50cb42588495679fcc01e09a9fb4f0e35f2483ed205681b3468ac2",
         "2e5a89b3fc873b02c0008f9a2290adc0c804a4287b9ea1939e070c332961f3a3"),
    "frontend/src/components/admin/AdminUserDrawer.jsx":
        ("7aa4001ee36dc657ceeacd9d50dbcf7c10fdaf5de7d63a9ee84e47cbe7e95de0",
         "97bc05d9f1711081b48bd2afb4359320048e78547180de81de9d87d2af856878"),
    "frontend/src/components/admin/AdminUsers.jsx":
        ("23614bb372a0c978c0a7551d45372026c6a5f1c18e838c5fdc938d5de75bd0e7",
         "f4e8789069fd5686732da3e33cf83aeda9233f1a6c72e18e751111c2f8256e13"),
    "frontend/src/components/admin/AdminVenues.jsx":
        ("79029d45379a552d651ffe1738b43cfac45949a5e8b37cdf291e17ce65109d93",
         "0c21718a2d6b9e84108dd67ac606919c767fe2a4838b3e9dcd15446a4df28ecf"),
    "frontend/src/components/admin/adminUi.jsx":
        ("755d3002cf7505da41bcd83e86f6f9cd79be4f6ca31f2abd02b2843385a6a94b",
         "768eadb900c5832c9797ebd511f20a2eea15d3e5608e33404d25b3993b72bbe2"),
    "frontend/src/components/lead/LeadTimesModal.jsx":
        ("b9001d606e490bb634a835896a8d0e8eb040e3524ec474a1e7c0c2584d44c980",
         "b37acb2e980beed7aefec022f3df383651f21c400f6c1419c344968dd2ab1469"),
    "frontend/src/components/manager/DownloadHoursModal.jsx":
        ("98c0f22f3c26b08f23f50065df20660f6cd307908a8c5d2c0f54e636c5c4fd6f",
         "d971ac89c2d83221036878a6198b9e20aefbd2314112fb1463e5bfba4104cf1d"),
    "frontend/src/components/manager/PayPeriodsModal.jsx":
        ("34379f873b6bc4a4e9fed412fd00ea80f8d45a7573dd4386109a9c4cacf4099a",
         "56b947ec1275035a0d494b81e5feec4d368a2eb1401a28d2c88b60d20b4c5a39"),
    "frontend/src/components/manager/TimeOffCard.jsx":
        ("2b4049b49b58d4a5f97141e545b7a908864f3ea81b46bc1fe25a592283dddd7b",
         "cf645e880c3b4c4b4dd8bd09febfb5879d565a3e07f516b7317a36dd9b547121"),
    "frontend/src/components/manager/TodayEventCard.jsx":
        ("ebd70e7689d566fe7ba65b05adf978ce71e7a0f9c5157b41c943737f735e11d4",
         "d346f12eed5a4b9ded8c9212f9f4243cae90eb374be117846f0a14c5c9145259"),
    "frontend/src/components/manager/TonightBoard.jsx":
        ("c62ae7382971a8c4b728577cc66dc5c3c6925904186c73f2ed46e82ba5cd3894",
         "5d06a25d9a1245c79d9b13dc85c4411f9f08105d825c5c468e2260a64f1f9236"),
    "frontend/src/components/profile/AboutSection.jsx":
        ("8d624f6495f9c316c03de82bb8663830dab64d605456de33afbfa845c5c0ea9a",
         "edf908a6f161c1044453ca86c91b6b20a9feadad1879faa3a6c90d0778a552a0"),
    "frontend/src/components/profile/AvailabilityEditor.jsx":
        ("9ca506b93359f3192129e777ec0ba404f981684c3cfd367a3ca8d7fc7ea787f9",
         "1726b171aadff4de91f9ae07be4c7e6def01d32502854807a76401827b47f91d"),
    "frontend/src/components/profile/CalendarSyncPanel.jsx":
        ("5d9e8e9f9c540a9bd80d94fbe6ca406b0157e20c17ce9ca0c080e69f5b37b714",
         "212223d3fe837c12d4d179862e6b08aa3e23dee17a212436f5c66bf0a82ee736"),
    "frontend/src/components/profile/CertificatesPanel.jsx":
        ("1ef8c611fd481b8e042a5d5b2f0fb5628ab84cbb9cd5aecdf09e511aa8351d81",
         "afeacae7c5d8605c00a2a6a69c9c513810b9feecb58e6e9c9200f5704a351c0b"),
    "frontend/src/components/profile/TimeOffPanel.jsx":
        ("dde45cef1a4924134b015288b3d8078762750f806f34a319e9990511d26ed11c",
         "c96aadb789a791dacda752adf4f07b02fc39180dd974b17362c82bb99d16855b"),
    "frontend/src/components/worker/CoverBoard.jsx":
        ("630283de990196196c0d6fe6ac8ced3d61f1870aef400643757d582492ac3b94",
         "eab7868fa043731a32a8b891ed9a2863bb1cc395111d9d626e6b2086802730ac"),
    "frontend/src/components/worker/CoverDialog.jsx":
        ("f7b79bb41b4b68b37dd3e2d0689ea29d464d9a2e7cbd7fa66dbd1d122a5427d7",
         "a129015f8bf983aa00bf0ec2d619526f4d91f5fbd95b424d8c10bb9aee84bc15"),
    "frontend/src/components/worker/EarningsCard.jsx":
        ("9109c349a58a83372d3b799feee8ff5bde067ef5528e34ced661e430f1ea5bd6",
         "170fb318e4753865178113b1d83b5a4d50a1ea2946ed1540bb6df73c52ee099a"),
    "frontend/src/components/worker/HandoffsPanel.jsx":
        ("eb72bdfb24644438cd0f6c929099c4f6733bcfc9d16e3f2eecba3136dae20b78",
         "7df52c90e24415c3a25663f794deceead31be4b01a84e9a5d3c68ea9852c65bb"),
    "frontend/src/components/worker/MyShiftCard.jsx":
        ("c036440dba7bdfc0b0939e780f3dcdf1ae7eb89552ab95dece5d09ee23ca51a5",
         "119e25fb4669d145cec059376f87e91167d0aee59d46457acc23de10f3225a6f"),
    "frontend/src/components/worker/WaitlistPanel.jsx":
        ("e495de77a71ffd808d182d84f41e8401d8b6c15b433bc66ae28d67cb47577d02",
         "fdb3c7bc8e44f5cec08864fba48473f9b71359f3bfcfdec91f3a704f1ad2136f"),
    "frontend/src/firebase.js":
        ("31bfc4285126f2f7ea15ee69b5cf019b117d542fe8caa8deade957b511788a6b",
         "50faa5a7e664df4ee2d477e6411f0231d8f07b8b7dffcb9d3407279a64c356c8"),
    "frontend/src/pages/AdminPanel.jsx":
        ("7fafdd4cc208cccd81aa615fabf0fc78c10191111552f343ced3e17eecba1bb5",
         "bd30c62f971cf4edddf8b52deb5f32a26ede259968d75f02095d02a091c94dcd"),
    "frontend/src/pages/EarningsPage.jsx":
        ("f3602f1349002ac9bd56350528fefd9c41751d6b0bab4e3aa7e3698e9677ff51",
         "6deb34e7b1a4e4b869d6954c5965b30ec5422dd0400a9b335e296ee04e696d49"),
    "frontend/src/pages/JoinPage.jsx":
        ("37b2b05115201525031e223a52ef5c1579c2383d23248a60e412f4565283ee92",
         "31a6fbcb7bc1e0437fc3d6263f84ce116960c2204795367bdaabf84cfe87dcf1"),
    "frontend/src/pages/LoginPage.jsx":
        ("84d3dcb5e8fd54975d7245873c59c1bb39053f96a7b29e8c8aec86556d4e6a87",
         "af17829738408a4993fdfb514bd07bc716a04659c2a15f039a1be44416a2d869"),
    "frontend/src/pages/OrganizationPage.jsx":
        ("d3f87b4048dca70c60fed14424a90a55c00bbb8f855bf3d8d8aa4edd86db5723",
         "73da3ecb0b471082ac1101b721db71b23ae48d04ccb07a068fed33f9a3490f80"),
    "frontend/src/pages/ProfilePage.jsx":
        ("227512a3a9f0ad79e9cd937910093138250da3d9cedadad4d347a22f701310f6",
         "514ae5b3f7f88856ae95c39a97911a5086d4a45a41b8a28a1ee9ab64eec80990"),
    "frontend/src/pages/PublicBoardPage.jsx":
        ("2d4874ca4dd3d9cc9eae3f3982736a49b14ff26b8008487619ec40269c6904e7",
         "bbf221700d976d13e65e3dc3cc585d48af2b342c63758754579d719db48032a8"),
    "frontend/src/pages/VenueManagerDashboard.jsx":
        ("9c770dbeba1ffb3131673b2fc0499661c666550cf17bba7793d53c7b6c5093e3",
         "860faf0fb10abb4007395531c7477cfb0f631d789141457d28384321658fcf74"),
    "frontend/src/pages/VenueProfile.jsx":
        ("7335344dccc0c9ca1967e7efcf967356d49ffe37a1d3f18712e90473bc93b01c",
         "4d083bbcc1a4abc6a0f371521571b69817e8bf241a86b0f30d5c8f7fda1b514d"),
    "frontend/src/pages/VenuesDirectory.jsx":
        ("f193ea50c23332bd5f13c6a6eacecffc7815a773e330f3899a2e7745b4ba97ef",
         "1455a69c4e35fb2eaa410aef7473805f6f82d12ae69950592f30dc1859fc7300"),
    "frontend/src/pages/WorkerDashboard.jsx":
        ("c471a08e4addd224cee8f5581f946bd641b5a5e7a59f9304d0f3f3e1e8d2d02d",
         "5d112d23375cb1f2ac1ce21fec25674791860ded7ccf955ec5292bcaab4b4937"),
    "frontend/src/utils/apiErrors.js":
        ("89bdca0d828c7a797f94dd54bda6dcd08ca616966cbc36a85eb49b716ba5e5b0",
         "d16d47e63fb8b7a1a39f0c91e05ba0e0dbb329c96f4bc1ad255fb0be8749b501"),
    "frontend/src/utils/push.js":
        ("af1d9682118b65de2885c3086fcd7dfc028f33c72377dc2d8cb760e3c6349363",
         "b2b154a5c2a09893aa6b2bb85095aa28222c77b37c78572674b93c7d2e4e28b3"),
    "product-roadmap.md":
        ("f249f19f61c4b28a7cb8cac3200f59ec88ffede5081aa4259d354fe1d7e6db54",
         "8faf46268e630bba0e100d81b4da833a4411dabccde3c0f387d21ee167443d54"),
}


# ---------------------------------------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------------------------------------
def candidates(root):
    """Every file the rules look at."""
    out = set(f for f in NAME_FILES + [p for p, _o, _n in SWAPS] if os.path.isfile(os.path.join(root, f)))
    for d in set(NAME_DIRS + COLOR_DIRS):
        for base, dirs, files in os.walk(os.path.join(root, d)):
            dirs[:] = [x for x in dirs if x not in ("__pycache__", "node_modules", "dist", ".vite")]
            for f in files:
                if f.endswith((".py", ".jsx", ".js", ".css")):
                    out.add(os.path.relpath(os.path.join(base, f), root).replace(os.sep, "/"))
    return sorted(out)


def fingerprint(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load(root, path, strict=True):
    """-> (text with LF line endings, True when the file uses Windows line endings)"""
    with open(os.path.join(root, path), "rb") as fh:
        raw = fh.read().decode("utf-8")
    crlf = raw.count("\r\n")
    if strict and crlf and crlf != raw.count("\n"):
        raise SystemExit("STOP: %s mixes Windows and Unix line endings. Nothing was changed." % path)
    return raw.replace("\r\n", "\n"), bool(crlf)


def main():
    args = sys.argv[1:]
    if [a for a in args if a != "--check"]:
        raise SystemExit("STOP: the only option is --check. Nothing was changed.")
    check_only = "--check" in args
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for need in ("frontend/src", "backend/src", "docker-compose.yaml"):
        if not os.path.exists(os.path.join(root, need)):
            raise SystemExit("STOP: %s not found under %s. This file belongs in <repo>/scripts/." % (need, root))

    todo, done, odd, missing = [], [], [], []
    for path in sorted(EXPECT):
        before, after = EXPECT[path]
        if not os.path.isfile(os.path.join(root, path)):
            missing.append(path)
            continue
        text, crlf = load(root, path)
        mark = fingerprint(text)
        if mark == after:
            done.append(path)
        elif mark == before:
            todo.append((path, text, crlf, after))
        else:
            odd.append(path)

    if not todo:
        print("Already applied: none of the %d files is in its 0.36.1 state. Nothing was changed." % len(EXPECT))
        return 0
    if missing or odd:
        for p in missing:
            print("  missing:    " + p)
        for p in odd:
            print("  unexpected: " + p + "   (not the 0.36.1 file, and not the finished file)")
        raise SystemExit("STOP: %d file(s) are not what this script was written against. Nothing was changed. "
                         "Report this list; do not edit the files or the script to get past it." % (len(missing) + len(odd)))

    results = []
    for path, text, crlf, after in todo:
        new = transform(text, path)
        if fingerprint(new) != after:
            raise SystemExit("STOP: %s: the result is not the expected one. Nothing was changed. "
                             "(Was this script edited?)" % path)
        results.append((path, new, crlf))

    extra = []
    for path in candidates(root):
        if path in EXPECT:
            continue
        text, _crlf = load(root, path, strict=False)
        if transform(text, path) != text:
            extra.append(path)
    if extra:
        for p in extra:
            print("  not in the list: " + p)
        raise SystemExit("STOP: %d file(s) outside the expected list use the old name or the old colours. Nothing was "
                         "changed. Report this list." % len(extra))

    if check_only:
        print("Check passed: %d file(s) would change, %d already done. Nothing was changed (--check)." % (len(results), len(done)))
        return 0
    for path, new, crlf in results:
        # written beside the file first and then swapped in, so a file is never left half written
        data = (new.replace("\n", "\r\n") if crlf else new).encode("utf-8")
        full = os.path.join(root, path)
        tmp = full + ".phase37.tmp"
        with open(tmp, "wb") as fh:
            fh.write(data)
        shutil.copymode(full, tmp)
        os.replace(tmp, full)
    print("Done: %d file(s) changed, %d were already done." % (len(results), len(done)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
