#!/usr/bin/env python3
"""
Phase 37.1 (0.37.1): buttons and selected tabs go back to green.

0.37.0 made the main buttons gold with dark text, which was hard to read. This script puts every button,
selected tab and other solid fill back exactly as it was before 0.37.0 (green), and leaves gold as the
accent colour: links, the current top-bar link, small icons, pay, focus rings, outlines and tints.

It changes whole lines, and only the lines listed in CHANGES below: each old line is replaced by its new line.
Nothing is worked out by rule, so the result is exactly the code that was tested.

How to run it, from the repository's root folder (the folder that has docker-compose.yaml):
    python scripts/phase371_buttons.py --check     look only: says what it would do and changes nothing
    python scripts/phase371_buttons.py             do it
On Linux or macOS the command may be "python3". It needs Python 3.8 or newer and nothing else.

It is safe:
  * Before it writes anything it checks every file against a SHA-256 fingerprint of the 0.37.0 file, and checks
    that its own result has the expected fingerprint. If anything differs it stops and changes nothing.
  * A file that is already done is skipped, so an interrupted run can be run again.
  * Each file is written beside the original and swapped in, so none is left half written.
  * Line endings are kept as they are.

DO NOT EDIT THIS FILE. If it stops with an error, report the message; do not change the lines or the fingerprints.
"""
import hashlib
import os
import shutil
import sys


# path -> [(the line as it is in 0.37.0, the line it becomes), ...]
CHANGES = {
    "backend/src/services/messaging.py": [
        ('  <a href="{html.escape(url)}" style="display:inline-block;background:#FDD400;color:#0a0a0a;text-decoration:none;font-weight:700;padding:10px 16px;border-radius:10px;font-size:14px">Open ShiftUp</a>',
         '  <a href="{html.escape(url)}" style="display:inline-block;background:#10b981;color:#0f172a;text-decoration:none;font-weight:700;padding:10px 16px;border-radius:10px;font-size:14px">Open ShiftUp</a>'),
    ],
    "frontend/public/offline.html": [
        ('      button { margin-top: 6px; padding: 12px 22px; border: 0; border-radius: 12px; background: #FDD400; color: #0a0a0a;',
         '      button { margin-top: 6px; padding: 12px 22px; border: 0; border-radius: 12px; background: #10b981; color: #020617;'),
    ],
    "frontend/public/sw.js": [
        ("const CACHE = 'shiftup-shell-v2';",
         "const CACHE = 'shiftup-shell-v3';"),
    ],
    "frontend/src/components/ActivityFeed.jsx": [
        ("              filter === f.id ? 'bg-brand-500 text-slate-950 border-brand-500' : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'",
         "              filter === f.id ? 'bg-emerald-500 text-slate-950 border-emerald-500' : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'"),
    ],
    "frontend/src/components/AppNudge.jsx": [
        ('            className="mt-2 px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '            className="mt-2 px-3 py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
    ],
    "frontend/src/components/ConfirmDialog.jsx": [
        ("            className={`px-5 py-2 rounded-xl text-sm font-bold disabled:opacity-50 ${danger ? 'bg-rose-600 hover:bg-rose-500 text-white' : 'bg-brand-500 hover:bg-brand-400 text-slate-950'}`}>",
         "            className={`px-5 py-2 rounded-xl text-sm font-bold disabled:opacity-50 ${danger ? 'bg-rose-600 hover:bg-rose-500 text-white' : 'bg-emerald-500 hover:bg-emerald-400 text-slate-950'}`}>"),
    ],
    "frontend/src/components/DuplicateEventModal.jsx": [
        ('        className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold disabled:opacity-50">',
         '        className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold disabled:opacity-50">'),
    ],
    "frontend/src/components/EventListingModal.jsx": [
        ('        <button type="button" onClick={onGoToSchedule} className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold">',
         '        <button type="button" onClick={onGoToSchedule} className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold">'),
        ('          className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold shadow-md shadow-brand-500/20 disabled:opacity-50 inline-flex items-center gap-1.5"',
         '          className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold shadow-md shadow-emerald-500/20 disabled:opacity-50 inline-flex items-center gap-1.5"'),
        ('                          className="px-2.5 py-1 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 font-bold disabled:opacity-50">Take it</button>',
         '                          className="px-2.5 py-1 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold disabled:opacity-50">Take it</button>'),
    ],
    "frontend/src/components/EventLocationPicker.jsx": [
        ('              className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '              className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
    ],
    "frontend/src/components/EventRosterModal.jsx": [
        ('                    className="px-2.5 py-1 rounded-lg bg-brand-600/15 hover:bg-brand-500 text-brand-300 hover:text-slate-950 text-xs font-bold border border-brand-600/30 inline-flex items-center gap-1">',
         '                    className="px-2.5 py-1 rounded-lg bg-emerald-600/15 hover:bg-emerald-600 text-emerald-300 hover:text-white text-xs font-bold border border-emerald-600/30 inline-flex items-center gap-1">'),
        ('                                className="px-2.5 py-1 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-40">',
         '                                className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-40">'),
        ('                              className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-brand-500 text-brand-300 hover:text-slate-950 border border-slate-700 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-40">',
         '                              className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-emerald-600 text-emerald-300 hover:text-white border border-slate-700 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-40">'),
    ],
    "frontend/src/components/EventTemplatesPanel.jsx": [
        ('          className="px-3.5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1.5 flex-shrink-0 self-start">',
         '          className="px-3.5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1.5 flex-shrink-0 self-start">'),
        ('                      className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1">',
         '                      className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1">'),
    ],
    "frontend/src/components/LocationFields.jsx": [
        ('            className="px-2.5 py-1 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-[11px] font-bold inline-flex items-center gap-1 disabled:opacity-50"',
         '            className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-[11px] font-bold inline-flex items-center gap-1 disabled:opacity-50"'),
    ],
    "frontend/src/components/ManagerQueues.jsx": [
        ('                    className="px-2.5 py-1 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-40">',
         '                    className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-40">'),
        ('                    className="px-2.5 py-1 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '                    className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
    ],
    "frontend/src/components/NotificationSettingsModal.jsx": [
        ('        className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold disabled:opacity-50">',
         '        className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold disabled:opacity-50">'),
    ],
    "frontend/src/components/PostedShiftsBoard.jsx": [
        ("      active ? 'bg-brand-500 text-slate-950 shadow-sm' : 'text-slate-400 hover:text-white'",
         "      active ? 'bg-emerald-600 text-white shadow-sm' : 'text-slate-400 hover:text-white'"),
        ('                            className="px-3 py-1.5 rounded-lg bg-brand-600/20 hover:bg-brand-500 text-brand-300 hover:text-slate-950 font-semibold text-xs border border-brand-600/30 transition inline-flex items-center gap-1.5"',
         '                            className="px-3 py-1.5 rounded-lg bg-emerald-600/20 hover:bg-emerald-600 text-emerald-300 hover:text-white font-semibold text-xs border border-emerald-600/30 transition inline-flex items-center gap-1.5"'),
        ('                              className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 font-bold text-xs transition inline-flex items-center gap-1.5 disabled:opacity-40"',
         '                              className="px-3 py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs transition inline-flex items-center gap-1.5 disabled:opacity-40"'),
    ],
    "frontend/src/components/PushDeviceCard.jsx": [
        ('            <button type="button" onClick={turnOn} disabled={busy} className={`${btn} bg-brand-500 hover:bg-brand-400 text-slate-950`}>',
         '            <button type="button" onClick={turnOn} disabled={busy} className={`${btn} bg-emerald-500 hover:bg-emerald-400 text-slate-950`}>'),
    ],
    "frontend/src/components/ReasonDialog.jsx": [
        ("        className={`px-5 py-2 rounded-xl text-sm font-bold disabled:opacity-50 ${danger ? 'bg-rose-600 hover:bg-rose-500 text-white' : 'bg-brand-500 hover:bg-brand-400 text-slate-950'}`}",
         "        className={`px-5 py-2 rounded-xl text-sm font-bold disabled:opacity-50 ${danger ? 'bg-rose-600 hover:bg-rose-500 text-white' : 'bg-emerald-500 hover:bg-emerald-400 text-slate-950'}`}"),
    ],
    "frontend/src/components/ReviewModal.jsx": [
        ('        className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '        className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
        ("                  className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${who === id ? 'bg-brand-500 text-slate-950 border-brand-500' : 'bg-slate-800 text-slate-300 border-slate-700'}`}>",
         "                  className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${who === id ? 'bg-emerald-500 text-slate-950 border-emerald-500' : 'bg-slate-800 text-slate-300 border-slate-700'}`}>"),
    ],
    "frontend/src/components/ShiftBoard.jsx": [
        ("                      ? 'bg-brand-500 text-slate-950 rounded-br-none'",
         "                      ? 'bg-emerald-600 text-white rounded-br-none'"),
    ],
    "frontend/src/components/ShiftEventFormModal.jsx": [
        ("  const primaryCls = 'px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold disabled:opacity-50 inline-flex items-center gap-1.5';",
         "  const primaryCls = 'px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold disabled:opacity-50 inline-flex items-center gap-1.5';"),
    ],
    "frontend/src/components/ShiftRosterModal.jsx": [
        ('                      className="px-3 py-1.5 rounded-lg bg-brand-600/20 hover:bg-brand-500 text-brand-300 hover:text-slate-950 text-xs font-semibold border border-brand-600/30 flex items-center space-x-1.5 transition self-end sm:self-center"',
         '                      className="px-3 py-1.5 rounded-lg bg-emerald-600/20 hover:bg-emerald-600 text-emerald-300 hover:text-white text-xs font-semibold border border-emerald-600/30 flex items-center space-x-1.5 transition self-end sm:self-center"'),
    ],
    "frontend/src/components/StaffPositionModal.jsx": [
        ('        className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-40"',
         '        className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-40"'),
        ('                          className="px-2.5 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold disabled:opacity-40">Book back</button>',
         '                          className="px-2.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold disabled:opacity-40">Book back</button>'),
        ('                    className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-brand-500 text-brand-300 hover:text-slate-950 border border-slate-700 text-xs font-bold disabled:opacity-40"',
         '                    className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-emerald-600 text-emerald-300 hover:text-white border border-slate-700 text-xs font-bold disabled:opacity-40"'),
    ],
    "frontend/src/components/TeamModal.jsx": [
        ("  'px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-40';",
         "  'px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-40';"),
        ("              className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap ${filter === id ? 'bg-brand-500 text-slate-950' : 'text-slate-300 hover:text-white'}`}>",
         "              className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap ${filter === id ? 'bg-emerald-500 text-slate-950' : 'text-slate-300 hover:text-white'}`}>"),
        ("            tab === id ? 'bg-brand-500 text-slate-950 border-brand-500' : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'",
         "            tab === id ? 'bg-emerald-500 text-slate-950 border-emerald-500' : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'"),
    ],
    "frontend/src/components/TimesheetModal.jsx": [
        ("            className={`px-3 py-1.5 rounded-lg text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50 ${f.kind === 'delete' || f.kind === 'noshow' ? 'bg-rose-600 text-white' : 'bg-brand-500 text-slate-950'}`}>",
         "            className={`px-3 py-1.5 rounded-lg text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50 ${f.kind === 'delete' || f.kind === 'noshow' ? 'bg-rose-600 text-white' : 'bg-emerald-600 text-white'}`}>"),
    ],
    "frontend/src/components/VenueLocationsPanel.jsx": [
        ('              className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '              className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
        ('              className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold disabled:opacity-50">',
         '              className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold disabled:opacity-50">'),
    ],
    "frontend/src/components/VenueSettingsModal.jsx": [
        ('            className="ml-auto px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '            className="ml-auto px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
        ("          className={`px-4 py-2 rounded-xl text-sm font-semibold transition ${tab === t.id ? 'bg-brand-500 text-slate-950' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}>",
         "          className={`px-4 py-2 rounded-xl text-sm font-semibold transition ${tab === t.id ? 'bg-emerald-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}>"),
        ('          className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold disabled:opacity-50">',
         '          className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold disabled:opacity-50">'),
        ('                  className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '                  className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
        ('                className="ml-auto px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1">',
         '                className="ml-auto px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1">'),
    ],
    "frontend/src/components/WorkerCalendar.jsx": [
        ("              className={`px-2.5 py-1 rounded-md text-xs font-semibold inline-flex items-center gap-1 ${view === 'month' ? 'bg-brand-500 text-slate-950' : 'text-slate-400'}`}>",
         "              className={`px-2.5 py-1 rounded-md text-xs font-semibold inline-flex items-center gap-1 ${view === 'month' ? 'bg-emerald-600 text-white' : 'text-slate-400'}`}>"),
        ("              className={`px-2.5 py-1 rounded-md text-xs font-semibold inline-flex items-center gap-1 ${view === 'list' ? 'bg-brand-500 text-slate-950' : 'text-slate-400'}`}>",
         "              className={`px-2.5 py-1 rounded-md text-xs font-semibold inline-flex items-center gap-1 ${view === 'list' ? 'bg-emerald-600 text-white' : 'text-slate-400'}`}>"),
        ("                          isToday ? 'bg-brand-500 text-slate-950' : inMonth ? 'text-slate-200' : 'text-slate-600'",
         "                          isToday ? 'bg-emerald-500 text-slate-950' : inMonth ? 'text-slate-200' : 'text-slate-600'"),
    ],
    "frontend/src/components/WorkerOffers.jsx": [
        ('                className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '                className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
    ],
    "frontend/src/components/WorkerProfilePanel.jsx": [
        ('                        className="px-2 py-1 rounded-md bg-brand-500 hover:bg-brand-400 text-slate-950 font-bold disabled:opacity-50">',
         '                        className="px-2 py-1 rounded-md bg-emerald-600 hover:bg-emerald-500 text-white font-bold disabled:opacity-50">'),
    ],
    "frontend/src/components/admin/AdminCreateUserModal.jsx": [
        ('            <button type="button" onClick={finish} className="px-5 py-2 rounded-xl text-sm font-bold bg-brand-500 hover:bg-brand-400 text-slate-950">Done</button>',
         '            <button type="button" onClick={finish} className="px-5 py-2 rounded-xl text-sm font-bold bg-emerald-500 hover:bg-emerald-400 text-slate-950">Done</button>'),
    ],
    "frontend/src/components/lead/LeadTimesModal.jsx": [
        ("            className={`px-3 py-1.5 rounded-lg text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50 ${f.kind === 'delete' || f.kind === 'noshow' ? 'bg-rose-600 text-white' : 'bg-brand-500 text-slate-950'}`}>",
         "            className={`px-3 py-1.5 rounded-lg text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50 ${f.kind === 'delete' || f.kind === 'noshow' ? 'bg-rose-600 text-white' : 'bg-emerald-600 text-white'}`}>"),
    ],
    "frontend/src/components/manager/DownloadHoursModal.jsx": [
        ("    on ? 'bg-brand-500 text-slate-950 border-brand-500' : 'bg-slate-950 text-slate-300 border-slate-700 hover:border-slate-500'}`;",
         "    on ? 'bg-emerald-500 text-slate-950 border-emerald-500' : 'bg-slate-950 text-slate-300 border-slate-700 hover:border-slate-500'}`;"),
        ('            className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '            className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
    ],
    "frontend/src/components/manager/PayPeriodsModal.jsx": [
        ('                          className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5">',
         '                          className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5">'),
        ('                            className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold disabled:opacity-50">',
         '                            className="px-3 py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold disabled:opacity-50">'),
    ],
    "frontend/src/components/manager/TimeOffCard.jsx": [
        ('                className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '                className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
    ],
    "frontend/src/components/profile/AboutSection.jsx": [
        ("            <label className={`px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1.5 cursor-pointer ${photoBusy ? 'opacity-50 pointer-events-none' : ''}`}>",
         "            <label className={`px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1.5 cursor-pointer ${photoBusy ? 'opacity-50 pointer-events-none' : ''}`}>"),
        ("                      <span className={`w-4 h-4 rounded border flex items-center justify-center ${on ? 'bg-brand-500 border-brand-500' : 'border-slate-600'}`}>",
         "                      <span className={`w-4 h-4 rounded border flex items-center justify-center ${on ? 'bg-emerald-500 border-emerald-500' : 'border-slate-600'}`}>"),
        ('          className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center justify-center gap-1.5 disabled:opacity-50">',
         '          className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center justify-center gap-1.5 disabled:opacity-50">'),
    ],
    "frontend/src/components/profile/AvailabilityEditor.jsx": [
        ('          className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '          className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
    ],
    "frontend/src/components/profile/CalendarSyncPanel.jsx": [
        ('            className={`${btn} bg-brand-500 hover:bg-brand-400 text-slate-950 disabled:opacity-50 flex-shrink-0`}>',
         '            className={`${btn} bg-emerald-500 hover:bg-emerald-400 text-slate-950 disabled:opacity-50 flex-shrink-0`}>'),
        ('              className={`${btn} bg-brand-500 hover:bg-brand-400 text-slate-950 disabled:opacity-50`}>',
         '              className={`${btn} bg-emerald-500 hover:bg-emerald-400 text-slate-950 disabled:opacity-50`}>'),
    ],
    "frontend/src/components/profile/CertificatesPanel.jsx": [
        ('          className="px-4 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '          className="px-4 py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
    ],
    "frontend/src/components/profile/TimeOffPanel.jsx": [
        ("  const seg = (on) => `px-3 py-1.5 rounded-lg text-xs font-bold transition ${on ? 'bg-brand-500 text-slate-950' : 'text-slate-300 hover:bg-slate-800'}`;",
         "  const seg = (on) => `px-3 py-1.5 rounded-lg text-xs font-bold transition ${on ? 'bg-emerald-600 text-white' : 'text-slate-300 hover:bg-slate-800'}`;"),
        ('          className="px-4 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '          className="px-4 py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
    ],
    "frontend/src/components/worker/CoverBoard.jsx": [
        ('                className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50 self-start sm:self-auto">',
         '                className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50 self-start sm:self-auto">'),
    ],
    "frontend/src/components/worker/CoverDialog.jsx": [
        ('            className="px-5 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold disabled:opacity-50">',
         '            className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold disabled:opacity-50">'),
    ],
    "frontend/src/components/worker/HandoffsPanel.jsx": [
        ('                className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">',
         '                className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold inline-flex items-center gap-1 disabled:opacity-50">'),
    ],
    "frontend/src/components/worker/MyShiftCard.jsx": [
        ('        <button type="button" onClick={onClockIn} disabled={busy === \'clock\'} className={`${btn} bg-brand-500 hover:bg-brand-400 text-slate-950`}>',
         '        <button type="button" onClick={onClockIn} disabled={busy === \'clock\'} className={`${btn} bg-emerald-600 hover:bg-emerald-500 text-white`}>'),
        ('      <button type="button" onClick={onClockIn} disabled={busy === \'clock\'} className={`${btn} bg-brand-500 hover:bg-brand-400 text-slate-950`}>',
         '      <button type="button" onClick={onClockIn} disabled={busy === \'clock\'} className={`${btn} bg-emerald-600 hover:bg-emerald-500 text-white`}>'),
    ],
    "frontend/src/components/worker/WaitlistPanel.jsx": [
        ('                    className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">',
         '                    className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 disabled:opacity-50">'),
    ],
    "frontend/src/index.css": [
        ('  background-color: #FDD400;   /* Phase 37: brand gold, dark text */',
         '  background-color: #059669;   /* 0.37.1: the selected view is a green button again */'),
        ('  border-color: #FEDE24;',
         '  border-color: #10b981;'),
        ('  color: #0a0a0a;',
         '  color: #ffffff;'),
    ],
    "frontend/src/pages/AdminPanel.jsx": [
        ('                className="px-4 py-2.5 rounded-xl bg-brand-500 hover:bg-brand-400 font-bold text-slate-950 text-xs inline-flex items-center gap-1.5">',
         '                className="px-4 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 font-bold text-slate-950 text-xs inline-flex items-center gap-1.5">'),
    ],
    "frontend/src/pages/EarningsPage.jsx": [
        ("                  period === p.id ? 'bg-brand-500 text-slate-950' : 'bg-slate-950 text-slate-300 border border-slate-800 hover:border-slate-600'}`}>",
         "                  period === p.id ? 'bg-emerald-500 text-slate-950' : 'bg-slate-950 text-slate-300 border border-slate-800 hover:border-slate-600'}`}>"),
    ],
    "frontend/src/pages/JoinPage.jsx": [
        ('          className="w-full py-2.5 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 font-bold text-sm">',
         '          className="w-full py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-sm">'),
        ('        className="w-full py-2.5 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 font-bold text-sm">',
         '        className="w-full py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-sm">'),
    ],
    "frontend/src/pages/LoginPage.jsx": [
        ('                className="w-full flex items-center justify-center py-2.5 px-4 rounded-xl bg-brand-500 hover:bg-brand-400 font-semibold text-slate-950 text-sm shadow-lg shadow-brand-500/20 transition disabled:opacity-50"',
         '                className="w-full flex items-center justify-center py-2.5 px-4 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 font-semibold text-slate-950 text-sm shadow-lg shadow-emerald-500/20 transition disabled:opacity-50"'),
        ('                    className="w-full mt-2 flex items-center justify-center py-2.5 px-4 rounded-xl bg-brand-500 hover:bg-brand-400 font-semibold text-slate-950 text-sm shadow-lg shadow-brand-500/20 transition focus:outline-none disabled:opacity-50"',
         '                    className="w-full mt-2 flex items-center justify-center py-2.5 px-4 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 font-semibold text-slate-950 text-sm shadow-lg shadow-emerald-500/20 transition focus:outline-none disabled:opacity-50"'),
    ],
    "frontend/src/pages/ProfilePage.jsx": [
        ("                tab === t.id ? 'bg-brand-500 text-slate-950' : 'text-slate-300 hover:bg-slate-800'}`}>",
         "                tab === t.id ? 'bg-emerald-600 text-white' : 'text-slate-300 hover:bg-slate-800'}`}>"),
        ('              className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5">',
         '              className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5">'),
    ],
    "frontend/src/pages/PublicBoardPage.jsx": [
        ('            className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 whitespace-nowrap">',
         '            className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-sm font-bold inline-flex items-center gap-1.5 whitespace-nowrap">'),
        ('                  className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-sm font-bold text-slate-950 inline-flex items-center gap-1.5">',
         '                  className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-sm font-bold text-slate-950 inline-flex items-center gap-1.5">'),
    ],
    "frontend/src/pages/VenueManagerDashboard.jsx": [
        ('              className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold transition inline-flex items-center gap-1.5 shadow-md shadow-brand-500/20"',
         '              className="px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold transition inline-flex items-center gap-1.5 shadow-md shadow-emerald-500/20"'),
    ],
    "frontend/src/pages/VenueProfile.jsx": [
        ("                    scope === s.id ? 'bg-brand-500 text-slate-950' : 'text-slate-400 hover:text-white'",
         "                    scope === s.id ? 'bg-emerald-600 text-white' : 'text-slate-400 hover:text-white'"),
        ('                            className="px-3.5 py-1.5 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold"',
         '                            className="px-3.5 py-1.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold"'),
    ],
    "frontend/src/pages/WorkerDashboard.jsx": [
        ("                  on ? 'bg-brand-500 text-slate-950 shadow-md shadow-brand-500/20' : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'}`}>",
         "                  on ? 'bg-emerald-500 text-slate-950 shadow-md shadow-emerald-500/20' : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'}`}>"),
        ("                      className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition ${whenFilter === w.id ? 'bg-brand-500 text-slate-950' : 'text-slate-400 hover:text-white'}`}>",
         "                      className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition ${whenFilter === w.id ? 'bg-emerald-600 text-white' : 'text-slate-400 hover:text-white'}`}>"),
    ],
}

# path -> (SHA-256 of the 0.37.0 file, SHA-256 of the finished file); of the text with Unix line endings, as UTF-8
EXPECT = {
    "backend/src/services/messaging.py":
        ("feeeaa6a56dff92b9af799c5d227362dc853f2d5d9b6da3a5d245bcad77a21ba",
         "47a3539ec46779c8517c8920e287ededb5a89fd8c787412bc33ebf9afde98c5f"),
    "frontend/public/offline.html":
        ("8299399eaa5536bead699d04621e9a79c1af74c2e96a9511be2b0cba7db84fb8",
         "6315be078a101d4026ec6ee141ccfeab2b269af3a6e0ea8b61d2bf8f8e66e069"),
    "frontend/public/sw.js":
        ("88efaeef04ce97267aa8117a5933fbc1331beac9d482cd1599cc8ed3e3a4aeba",
         "6011fdcf56bb65559d4fd5b58ee059c392ccda1c15a85444568a6eb334415473"),
    "frontend/src/components/ActivityFeed.jsx":
        ("c01e52b55db5c242fd525766f83d792085fd5f5d2ae14e5ab006fe29fc37ad8e",
         "bd654789896c544989ca38cafc1666256a56dbe5e30e190264892f6980c84bbb"),
    "frontend/src/components/AppNudge.jsx":
        ("2df45e121eabc7f932e5bfbdd4efa2d48d5fd1228eb03bc8f5d5f526276a18e1",
         "81d4ea85bbd626b7b983364ab979ada527f0f244cdb4ca7ad4286bb726dd0c09"),
    "frontend/src/components/ConfirmDialog.jsx":
        ("67b42f030e5c9ed3f878a0adf587fca0820ca762b1fb048e00bb30c1778053d9",
         "4e9182dec2628bac51738c35f3c242281f7037ed6a483ee52b6d6fc78ddaa756"),
    "frontend/src/components/DuplicateEventModal.jsx":
        ("328422c2b4250166d6b60153551ca5151e64131ba799bff22276b30abdd9abc0",
         "401908199a688b06db431439870eaec8e07bc230b280fbcbf3280d35cd122a36"),
    "frontend/src/components/EventListingModal.jsx":
        ("1f628f8bbd16d20d0bc1220977765111a81cb4fd162528234f0f1b09738434dd",
         "60dc5c3d2fabdc0fb3925bf665989e9feacb06033c8d132df70bfe85ea8c28c3"),
    "frontend/src/components/EventLocationPicker.jsx":
        ("eb2d36c36332523dbb0674f27d9cfd8ea0368afba4de029972c9f95e0c807f51",
         "15bc175deac8c6560eb0ca470346d53885a396fea6d4799de22245fb7c4ea350"),
    "frontend/src/components/EventRosterModal.jsx":
        ("a81b45d31e18b4a591df29313cfc6a6450763959b35d09749002b4c3746362e3",
         "9271764ff010a9f2e1a889f1735db819ccf711b2b0aaeea7381eeff53caa50ae"),
    "frontend/src/components/EventTemplatesPanel.jsx":
        ("d89948e9d1625b51a1442116857d61dd79457074481d4da6710461a5f9b829b1",
         "eb60f4a34c892722649685af6165475e2d243f2de2cfc2ccc5caba9417aa521d"),
    "frontend/src/components/LocationFields.jsx":
        ("bc74d927593d84234ef50947daf2baf88b1080fb204fdc41a50b02ac8340d4e7",
         "e084013097617edc194e9b0589c0f21cf3f336e9062b389d60815041c4111a0e"),
    "frontend/src/components/ManagerQueues.jsx":
        ("c9412274c3268f4f8672519cff1a6abf91a8ca0ca86c45c54a411c4663c70ae8",
         "2e2661d25fdc95b1b422f204d3d92abe55c818140d6f37a09d97ebddb80a32b4"),
    "frontend/src/components/NotificationSettingsModal.jsx":
        ("91374ae64d447e83a1e1d5c9e472050e0f083bea45dd49dc91afdf1bed8685f9",
         "a82137d2dc035ae9688a7c43a50787de2a5cb42941aef1fb3a04e35b8f0af496"),
    "frontend/src/components/PostedShiftsBoard.jsx":
        ("a7173f9924982ce17eeb3f403c1da58365e146d931b022f6987ef33dcf4be413",
         "016896a79c1e1df6ecc26474610b460823e157fc2c4af6ae77cf857be02f00a0"),
    "frontend/src/components/PushDeviceCard.jsx":
        ("3b46efe306576485b9ade752a2436a3fc37e90f029b9a52bbe1903f93ea026d9",
         "88772e310ae7a65f9b7f24b66d0ca7078f4d050a18ccad18dd4cae2e60df4631"),
    "frontend/src/components/ReasonDialog.jsx":
        ("d150af150a68ac63f0ea2072151a3b9c55636677d134d53576ea4d224288ed99",
         "5f06d594abc8996440f28a08df0066151ab78f29045ad4e6b09b091e45ab92a6"),
    "frontend/src/components/ReviewModal.jsx":
        ("369573cd745cd54cf0004605e280a5b39d73191d4e0d61624364e6c14e8481aa",
         "f7005dafd9edd0b3df66eee9bad3e5cfff1577b62bc8ea9915d4ebbf10ba329d"),
    "frontend/src/components/ShiftBoard.jsx":
        ("a63958a1fe67efa017f21ffdd2072a6248abb1cdcf82018fbf0000a3aad290de",
         "764457309fffb69827b19e028e08f6f335105a3c1be085c91bd196732998f47c"),
    "frontend/src/components/ShiftEventFormModal.jsx":
        ("2574e43468ba60b5112c8e171a93332305d6f08f59969b4ebb18bdff6867ce71",
         "e2a26ce48632d025947f8d1530e25c16aff632fc034b1c706cac5a58a5e040ad"),
    "frontend/src/components/ShiftRosterModal.jsx":
        ("747624aa0c54ef2f73628a3b4f264586089167092c5f6d6719111e06adf7b1da",
         "b4348cd75fbebf4bc248c08a30430736850057c1499b79e99a299b33a5d4679a"),
    "frontend/src/components/StaffPositionModal.jsx":
        ("005018f51d9132c04b62fc7ec140149f31d0c868011cb51f59489b29e20582eb",
         "0320e04c812a85d83828cf7008fe15e49a90dd82d5360e36e1124d595a6a247b"),
    "frontend/src/components/TeamModal.jsx":
        ("2560e4eda262d328993129bf17a6bc1bce07fcaf464c96ed989c99d645beda52",
         "7b7a896d12c7b8afe82eb40d876c96017747ffdfba153d7421ce716e4a45b7dd"),
    "frontend/src/components/TimesheetModal.jsx":
        ("f0561b983bc64a7dba78cd6da8a2ca5b820dba308c750774325757de4237f70f",
         "8b88a9e3325cdcc8383bb36e0138d7cc9b893f3541b3543ca7009de845516e2a"),
    "frontend/src/components/VenueLocationsPanel.jsx":
        ("3efade5d34a8f04c11ce813299ee58b1f17a7ede8fae76750fe05ed50aad8d17",
         "4892ff51760b4afc49a2559ff6c4fa5e7d4437e03cd7120e125f22242c0cb31e"),
    "frontend/src/components/VenueSettingsModal.jsx":
        ("fd71afdb1ceca5f6ee6f704e2315862c83afc4461be185ebb63fdb8efecb6f44",
         "ae86918d12104619fb4c25232324ad11488543e2697af08f83156341ec89d316"),
    "frontend/src/components/WorkerCalendar.jsx":
        ("5f27d76fea6e87023adc2e6a73afeff234d1cbedb4060d9c7f88bb40e40df761",
         "1544fbe0ede1bf95ee5f119191d44e35f7cd072f8ff1e46e46e6ba4022b9d03a"),
    "frontend/src/components/WorkerOffers.jsx":
        ("cf58b49db93750cff73e79ae1430979ff506f874a43b222819d2d8b7d86885bb",
         "c952b9f14b30620dfeb091a17168b5fe53d965d6cccb674ca383c477df06a859"),
    "frontend/src/components/WorkerProfilePanel.jsx":
        ("eed385c3eb63e3bec9031833fc2d01d0520de21a6a59fe6efedf01a0cc538ea3",
         "ea204a40d07d9630e711cdd23961bdecbe4f2a30cec1d609c6023ff6ee7a5488"),
    "frontend/src/components/admin/AdminCreateUserModal.jsx":
        ("e5dff85bea075da196382d6f19957faf5ea207d86925b83b81fbe908008591b7",
         "6274dea1bc17d3de65e32b069a0303c93a1dd71f23e889569c4dde8bd4dc94b9"),
    "frontend/src/components/lead/LeadTimesModal.jsx":
        ("b37acb2e980beed7aefec022f3df383651f21c400f6c1419c344968dd2ab1469",
         "b9001d606e490bb634a835896a8d0e8eb040e3524ec474a1e7c0c2584d44c980"),
    "frontend/src/components/manager/DownloadHoursModal.jsx":
        ("d971ac89c2d83221036878a6198b9e20aefbd2314112fb1463e5bfba4104cf1d",
         "805073247fa95b30513dc4cf003d55412bc20028135b348ea81beef2bad6e139"),
    "frontend/src/components/manager/PayPeriodsModal.jsx":
        ("56b947ec1275035a0d494b81e5feec4d368a2eb1401a28d2c88b60d20b4c5a39",
         "7b77f0323f941ba4ade719f0b75ca0c9417cbfd0b475b3829d398a4c430b2887"),
    "frontend/src/components/manager/TimeOffCard.jsx":
        ("cf645e880c3b4c4b4dd8bd09febfb5879d565a3e07f516b7317a36dd9b547121",
         "4e798b3e989ff392bab4e29a983240291632b69538222938291171bc540b233e"),
    "frontend/src/components/profile/AboutSection.jsx":
        ("edf908a6f161c1044453ca86c91b6b20a9feadad1879faa3a6c90d0778a552a0",
         "97fa1682be46596593d64c797ec35382cb0bedfbe229b7a5b44d623ff35feef7"),
    "frontend/src/components/profile/AvailabilityEditor.jsx":
        ("1726b171aadff4de91f9ae07be4c7e6def01d32502854807a76401827b47f91d",
         "ca97ce5628f449e1fdb86be4c4df09443dcb7ad845946d574f54dfeb3654e522"),
    "frontend/src/components/profile/CalendarSyncPanel.jsx":
        ("212223d3fe837c12d4d179862e6b08aa3e23dee17a212436f5c66bf0a82ee736",
         "c16d9f01e7777cd7867e3d88f857d1e6972eaaa65329ab1de6903bce6dcf8c31"),
    "frontend/src/components/profile/CertificatesPanel.jsx":
        ("afeacae7c5d8605c00a2a6a69c9c513810b9feecb58e6e9c9200f5704a351c0b",
         "3fe9ca6a97440b5546576a18ae9ae6c14290a19330560fce9912bd6ee02e7fcc"),
    "frontend/src/components/profile/TimeOffPanel.jsx":
        ("c96aadb789a791dacda752adf4f07b02fc39180dd974b17362c82bb99d16855b",
         "f80f6cfdf6a14e0c978cff15d2ebf315cb7236e71a73e76874b8d510c8ed7bf6"),
    "frontend/src/components/worker/CoverBoard.jsx":
        ("eab7868fa043731a32a8b891ed9a2863bb1cc395111d9d626e6b2086802730ac",
         "ac2051f39e49007bee144d218b08729c92b7c0f66dca32d0b264408b9688b51b"),
    "frontend/src/components/worker/CoverDialog.jsx":
        ("a129015f8bf983aa00bf0ec2d619526f4d91f5fbd95b424d8c10bb9aee84bc15",
         "b9afdf020ca13372103f13650bbe895c0ff345e0813ba1e3c52a9bbd17dc7ae0"),
    "frontend/src/components/worker/HandoffsPanel.jsx":
        ("7df52c90e24415c3a25663f794deceead31be4b01a84e9a5d3c68ea9852c65bb",
         "ea496b6178ac959b5018bbb414acc1dd2de87d25b67390f8e512d6816c0b64a8"),
    "frontend/src/components/worker/MyShiftCard.jsx":
        ("119e25fb4669d145cec059376f87e91167d0aee59d46457acc23de10f3225a6f",
         "5582c1024d3bf06c94f14827180943240cf8fbab3a0208c4905fbfb33f8f9181"),
    "frontend/src/components/worker/WaitlistPanel.jsx":
        ("fdb3c7bc8e44f5cec08864fba48473f9b71359f3bfcfdec91f3a704f1ad2136f",
         "e495de77a71ffd808d182d84f41e8401d8b6c15b433bc66ae28d67cb47577d02"),
    "frontend/src/index.css":
        ("302970cb61528f162d7d58a6abc90fa412d212dba9d38d9561dcb4d8d190d113",
         "d035f01abac7a31ca0b8c06e46083a73b7602b47ba8be9ff07a2d55d68ed9fad"),
    "frontend/src/pages/AdminPanel.jsx":
        ("bd30c62f971cf4edddf8b52deb5f32a26ede259968d75f02095d02a091c94dcd",
         "7fafdd4cc208cccd81aa615fabf0fc78c10191111552f343ced3e17eecba1bb5"),
    "frontend/src/pages/EarningsPage.jsx":
        ("6deb34e7b1a4e4b869d6954c5965b30ec5422dd0400a9b335e296ee04e696d49",
         "dcb4cdaad11b8c3a3cb9859691ff03acb4b97c48c6878b572b6c338d3688a806"),
    "frontend/src/pages/JoinPage.jsx":
        ("5a2db8c8b1ac28b85fba71c30ee0a545b21c554ef8a954f37115c5110075bdc8",
         "0ae6413d9faaa9765b90a2572a69b6df187cab4f67ed2b36f1e620bc8375de07"),
    "frontend/src/pages/LoginPage.jsx":
        ("04a5d69d92c60f3d81d5d1fecc8622a34de929394b61631a27dc48ec6b2cde05",
         "e6916d10e4fbe64d059113d872f214938294f8ebe762913c9f50295580c95da3"),
    "frontend/src/pages/ProfilePage.jsx":
        ("514ae5b3f7f88856ae95c39a97911a5086d4a45a41b8a28a1ee9ab64eec80990",
         "227512a3a9f0ad79e9cd937910093138250da3d9cedadad4d347a22f701310f6"),
    "frontend/src/pages/PublicBoardPage.jsx":
        ("3c88e01e11e785a5f5392922d3a8a41b7fa59e3c512e5e4b4c06260e15321aee",
         "c2377462e071f80351bde8c0e01eeb87b1194626ca2b227bd4dedb5f38c45cae"),
    "frontend/src/pages/VenueManagerDashboard.jsx":
        ("860faf0fb10abb4007395531c7477cfb0f631d789141457d28384321658fcf74",
         "136e4e3b53c1cf3e04a9e9dd1e5b13410397f8349d5d295c786db6128f36eb2e"),
    "frontend/src/pages/VenueProfile.jsx":
        ("4d083bbcc1a4abc6a0f371521571b69817e8bf241a86b0f30d5c8f7fda1b514d",
         "89e83751e2b370976b773e73805c25ce92d26518722eea8f35a719332e5f1e17"),
    "frontend/src/pages/WorkerDashboard.jsx":
        ("d3a46035fabdc34b356462668a3d0b339f0227d95842c93862cf64831ecd9c88",
         "6533237a3c370f7370e6abc193eb5bc6891510ea0a17390963cdcff7610f20ad"),
}


def fingerprint(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load(root, path):
    """-> (text with LF line endings, True when the file uses Windows line endings)"""
    with open(os.path.join(root, path), "rb") as fh:
        raw = fh.read().decode("utf-8")
    crlf = raw.count("\r\n")
    if crlf and crlf != raw.count("\n"):
        raise SystemExit("STOP: %s mixes Windows and Unix line endings. Nothing was changed." % path)
    return raw.replace("\r\n", "\n"), bool(crlf)


def apply(text, pairs, path):
    table = dict(pairs)
    lines = text.split("\n")
    seen = set()
    for i, line in enumerate(lines):
        if line in table:
            seen.add(line)
            lines[i] = table[line]
    if len(seen) != len(table):
        raise SystemExit("STOP: %s: %d of its %d lines were not found. Nothing was changed." % (path, len(table) - len(seen), len(table)))
    return "\n".join(lines)


def main():
    args = sys.argv[1:]
    if [a for a in args if a != "--check"]:
        raise SystemExit("STOP: the only option is --check. Nothing was changed.")
    check_only = "--check" in args
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for need in ("frontend/src", "backend/src", "docker-compose.yaml"):
        if not os.path.exists(os.path.join(root, need)):
            raise SystemExit("STOP: %s not found under %s. This file belongs in <repo>/scripts/." % (need, root))
    if sorted(CHANGES) != sorted(EXPECT):
        raise SystemExit("STOP: this script is damaged (its two lists don't match). Nothing was changed.")

    todo, done, odd, missing = [], [], [], []
    for path in sorted(EXPECT):
        before, after = EXPECT[path]
        if not os.path.isfile(os.path.join(root, path)):
            missing.append(path)
            continue
        text, crlf = load(root, path)
        mark = fingerprint(text)
        if mark == after:
            done.append(path)
        elif mark == before:
            todo.append((path, text, crlf, after))
        else:
            odd.append(path)

    if missing or odd:
        for p in missing:
            print("  missing:    " + p)
        for p in odd:
            print("  unexpected: " + p + "   (not the 0.37.0 file, and not the finished file)")
        raise SystemExit("STOP: %d file(s) are not what this script was written against. Nothing was changed. "
                         "Report this list; do not edit the files or the script to get past it." % (len(missing) + len(odd)))
    if not todo:
        print("Already applied: all %d files are done. Nothing was changed." % len(EXPECT))
        return 0

    results = []
    for path, text, crlf, after in todo:
        new = apply(text, CHANGES[path], path)
        if fingerprint(new) != after:
            raise SystemExit("STOP: %s: the result is not the expected one. Nothing was changed. "
                             "(Was this script edited?)" % path)
        results.append((path, new, crlf))

    if check_only:
        print("Check passed: %d file(s) would change, %d already done. Nothing was changed (--check)." % (len(results), len(done)))
        return 0
    for path, new, crlf in results:
        data = (new.replace("\n", "\r\n") if crlf else new).encode("utf-8")
        full = os.path.join(root, path)
        tmp = full + ".phase371.tmp"
        with open(tmp, "wb") as fh:
            fh.write(data)
        shutil.copymode(full, tmp)
        os.replace(tmp, full)
    print("Done: %d file(s) changed, %d were already done." % (len(results), len(done)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
